[package]
name = "midgar"
version = "0.1.0"
authors = ["Gabriel Martinez <reitaka@gmail.com>"]

[dependencies]
cgmath = "^0.9.1"
glutin = "^0.5.0"
glium = "^0.14.0"
image = "^0.9.0"
# rand = "^0.3.0"
